apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: configmap-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "while true; do echo hi; sleep 10; done" ]
      env:
        - name: COMPANY
          valueFrom:
            configMapKeyRef:
              name: literal-config
              key: company
        - name: LOCATION
          valueFrom:
            configMapKeyRef:
              name: yaml-config
              key: location
        - name: BUSINESS
          valueFrom:
            configMapKeyRef:
              name: yaml-config
              key: business
      envFrom:
        - configMapRef:
            name: file-env-config
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: file-config
  restartPolicy: Never